version: '3.8'

services:
 postgres:
    build:
      context: /home/kevin/simplon_wsl/briefs/b16_meteo_assistant/repo_b16/postgres
    image: postgres
    container_name: postgres_container
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./start-postgres.sh:/docker-entrypoint-initdb.d/
    networks:
      - my_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5
      timeout: 5s
      start_period: 20s

 mf_data_batch:
    build:
      context: /home/kevin/simplon_wsl/briefs/b16_meteo_assistant/repo_b16/meteofrance_data
    image: data_batch
    container_name: batch_container
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./scripts:/scripts
    networks:
      - my_network

 mf_report_gen:
    build:
      context: /home/kevin/simplon_wsl/briefs/b16_meteo_assistant/repo_b16/weather_report_gen
    image: report_gen
    container_name: report_gen_container
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    networks:
      - my_network

 mf_front:
    build:
      context: /home/kevin/simplon_wsl/briefs/b16_meteo_assistant/repo_b16/front
    image: front
    container_name: front_container
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - my_network

networks:
 my_network:
    driver: bridge

volumes:
 postgres-data:
